# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86fb7bd13905acd9b79c2fa27f97d5b4fe4a746c03f0be69deab23348399d401d8252d8d09faf36b9dced6d119a55a44cc8887ebc7dfedde8c151b9fe2ef36dc

test:
  secret_key_base: b8ebf4a27363ebe2d9b71b8137835e3e88235ce7973463bdd7f03d7d2fdf7432715ad8844cbd06ec9ef87f7ff378da4d4bbb6888e3bf32e4eedcbc12ce7e03bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
